# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2019-12-26 10:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-updated', '-timestamp']},
        ),
    ]
